- name: Launch remote script
  hosts: all
  become: true
  tasks:
    - name: Launch script after change folder
      ansible.builtin.shell: ./ScriptToUse.sh
      args:
        chdir: /path/to/folder
